apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgeflow
resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-configmap.yaml
  - 03-postgres.yaml
  - 04-redis.yaml
  - 05-kafka.yaml
  - 06-minio.yaml
  - 07-api.yaml
  - 08-worker.yaml
  - 09-frontend.yaml
  - 10-ingress.yaml
